name: ai_news
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.14.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  velocity_x: 3.3.0
  audioplayers: 0.20.1
  google_fonts: 2.1.0
  alan_voice: 3.0.0
  flutter_tts: 3.2.2
  speech_to_text: ^5.1.1
  avatar_glow: ^2.0.2
  url_launcher: ^6.0.12
  clipboard: ^0.1.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

